### ISSUE TITLE
Readonly форма

### ISSUE THREAD

**Issue by gemcave** [NursErgesh/django_2gis_maps#5]
Спасибо за библиотеку, у меня только одна проблема в админке поля(добавленные библиотекой) редактируются, а в обычной форме нет. Это задел на будущее, или моя ошибка при подключении?

**Comment by NursErgesh** [comment]
Дело в том, что `AddressField` и `GeolocationField` используют специальные `id` к которым крепится JS код, если этих параметров нет, то не будет работать.
Но для более детального ответа, прошу выслать кусок когда, где вы его хотите использовать

**Comment by gemcave** [comment]
Самая обычная форма:

**views.py**
```
class CreateProductView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/product_new.html'

    def get_object(self, queryset=None):
        return self.model.objects.first()

```

**forms.py**
```
from django_2gis_maps.widgets import DoubleGisMapsAddressWidget

class ProductForm(forms.ModelForm):
    description = forms.CharField(widget=CKEditorWidget, label='')
    address = DoubleGisMapsAddressWidget()
```
**product_new**
```
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load doublegis %}

{% block content %}
    <div class="container mt-4">
        <h1>Новый товар</h1>
        <form method="POST" class="form" enctype="multipart/form-data">{% csrf_token %}
            {{ form.media }}
            {{  form | crispy }}
            {% render_map view.get_object width="100%" height="400px"%}
            <button type="submit" class="btn btn-primary">Добавить</button>
        </form>
    </div>
{% endblock %}
```

**Comment by NursErgesh** [comment]
Дело в том, что эта библиотека предназначена для использования его, исключительно в админке. А на сколько я понял, вы хотите использовать эту фичу для клиентской части вашего проекта, для добавления нового товара...
Предполагаю что у `input` в вашей форме нет `id` который указан в `JS` и `CSS` файлах, которые используются внутри `DoubleGisMapsAddressWidget`,
к тому же вы как поле используете не `CharField`, а сам виджет
попробуйте так:
```py
from django_2gis_maps.widgets import DoubleGisMapsAddressWidget

class ProductForm(forms.ModelForm):
    description = forms.CharField(widget=CKEditorWidget, label='')
    address = forms.CharField(widget=DoubleGisMapsAddressWidget())

```

**Comment by gemcave** [comment]
Спасибо за помощь, заработало. Два дня мучал себя с ymaps и 2-мя библиотеками с гугл картами, в итоге только в вашей был нормальный пример без такой шизофрении как api-key.
